# Python CircleCI 2.1 configuration file
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.10

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            conda create -n testenv -e requirements.txt python=3.10
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            source activate testenv
            pytest -v --cov=bic_pytorch
